package com.spring.testing.integrationtesting;

import com.spring.testing.Entity.Student;
import com.spring.testing.dto.StudentRequest;
import com.spring.testing.repository.StudentRepository;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import tools.jackson.databind.ObjectMapper;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 ============================================================================
                    Integration Test (Real Spring Boot Test)
 ============================================================================

 ✔ Loads the complete Spring Boot Application Context.

 ✔ Uses the real:
      - Controller
      - Service
      - Repository
      - Database (H2)
      - Exception Handler

 ✔ No mocking is involved.

 Purpose:
 --------
 Verify that the complete application flow works correctly.

 Client
    ↓
 Controller
    ↓
 Service
    ↓
 Repository
    ↓
 H2 Database
    ↓
 Response

 ============================================================================
*/

@SpringBootTest                     // Loads the complete Spring Boot application //
@AutoConfigureMockMvc               // Creates MockMvc for sending fake HTTP requests
@ActiveProfiles("test")             // Uses application-test.properties
class StudentIntegrationTest {

    /*
    ------------------------------------------------------------------------
                            Test Dependencies
    ------------------------------------------------------------------------
    */

    @Autowired
    private MockMvc mockMvc;         // Simulates HTTP requests

    @Autowired
    private ObjectMapper objectMapper; // Converts Java Object ↔ JSON

    @Autowired
    private StudentRepository studentRepository; // Used to verify DB state


    /*
    ------------------------------------------------------------------------
                          Runs Before Every Test
    ------------------------------------------------------------------------

    Why?

    Since every test shares the same H2 database,
    we delete all records before each test so that
    every test starts with a clean database.

    This keeps tests independent.

    Test 1
      ↓
    Inserts Data
      ↓
    Before Test 2
      ↓
    deleteAll()
      ↓
    Empty Database
    */

    @BeforeEach
    void cleanDatabase() {
        studentRepository.deleteAll();
    }


    /*
    ==========================================================================
                                CREATE STUDENT
    ==========================================================================
    */

    @Test
    void shouldSaveStudentAndReturnStudentWithStatusCreated() throws Exception {

        /*
        ----------------------------------------------------------------------
        Arrange

        Prepare request data exactly like a client would send.
        ----------------------------------------------------------------------
        */

        StudentRequest request = createStudentRequest(
                "Sapphire",
                23,
                91
        );


        /*
        ----------------------------------------------------------------------
        Act

        Send POST request.

        MockMvc behaves like Postman but inside the JVM.
        ----------------------------------------------------------------------
        */

        mockMvc.perform(post("/students")

                        // HTTP Header
                        .contentType(MediaType.APPLICATION_JSON)

                        // HTTP Body
                        .content(objectMapper.writeValueAsString(request)))

                /*
                --------------------------------------------------------------
                Assert HTTP Response
                --------------------------------------------------------------
                */

                .andExpect(status().isCreated())

                // Generated by database
                .andExpect(jsonPath("$.id").exists())

                .andExpect(jsonPath("$.name").value("Sapphire"))
                .andExpect(jsonPath("$.age").value(23))
                .andExpect(jsonPath("$.marks").value(91));


        /*
        ----------------------------------------------------------------------
        Assert Database

        Integration Tests should also verify that
        the database contains the expected data.
        ----------------------------------------------------------------------
        */

        Assertions.assertEquals(
                1,
                studentRepository.count()
        );

        Student savedStudent = studentRepository
                .findByName("Sapphire")
                .orElseThrow();

        Assertions.assertEquals(
                "Sapphire",
                savedStudent.getName()
        );

        Assertions.assertEquals(
                23,
                savedStudent.getAge()
        );

        Assertions.assertEquals(
                91,
                savedStudent.getMarks()
        );
    }


    /*
    ==========================================================================
                            GET STUDENT (Success)
    ==========================================================================
    */

    @Test
    void shouldReturnStudentWhenStudentExists() throws Exception {

        /*
        ----------------------------------------------------------------------
        Arrange

        Seed database with required data.

        Since GET requires existing data,
        we insert a student first.
        ----------------------------------------------------------------------
        */

        studentRepository.save(

                createStudent(
                        "Sapphire",
                        23,
                        91
                )
        );


        /*
        ----------------------------------------------------------------------
        Act + Assert
        ----------------------------------------------------------------------
        */

        mockMvc.perform(

                        get("/students")

                                .queryParam(
                                        "name",
                                        "Sapphire"
                                )
                )

                .andExpect(status().isOk())

                .andExpect(jsonPath("$.id").exists())

                .andExpect(jsonPath("$.name")
                        .value("Sapphire"))

                .andExpect(jsonPath("$.age")
                        .value(23))

                .andExpect(jsonPath("$.marks")
                        .value(91));
    }


    /*
    ==========================================================================
                            GET STUDENT (Not Found)
    ==========================================================================
    */

    @Test
    void shouldReturnNotFoundWhenStudentDoesNotExist() throws Exception {

        /*
        Database is empty because of @BeforeEach.

        Therefore requesting "Diamond"
        should trigger StudentNotFoundException.
        */

        mockMvc.perform(

                        get("/students")

                                .queryParam(
                                        "name",
                                        "Diamond"
                                )
                )

                .andExpect(status().isNotFound())

                // Response produced by GlobalExceptionHandler
                .andExpect(jsonPath("$.error")
                        .value("Student not found with name : Diamond"));
    }


    /*
    ==========================================================================
                            Helper Methods
    ==========================================================================

    Why helper methods?

    ✔ Avoid repeating object creation.
    ✔ Keep tests small.
    ✔ Improve readability.
    ✔ Easy to modify common test data.

    Important Note:Creating Helpers is a perfect idea when, we need to repeat at too many places. But it's already a
     very few places, then repeating the logic is a feasible approach rather.

    */

    //For StudentRequest
    private StudentRequest createStudentRequest(
            String name,
            int age,
            int marks
    ) {

        StudentRequest request = new StudentRequest();

        request.setName(name);
        request.setAge(age);
        request.setMarks(marks);

        return request;
    }

    //For Student Entity
    private Student createStudent(
            String name,
            int age,
            int marks
    ) {

        return Student.builder()
                .name(name)
                .age(age)
                .marks(marks)
                .build();
    }

}