spring.application.name=Revisebackend

spring.output.ansi.enabled=ALWAYS
logging.pattern.console=${LOGGING_CONSOLE_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx}
server.port=8081
#-------------------------------------------------

#H2 Db setup
#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:h2:file:D:/Java Backend/test;AUTO_SERVER=true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 Console (for viewing tables & data)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=never
#the above property is for .sql files only, Means when to run those file.

#-------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
